print("1","This is line 1")
print("2","This is line 2")
print("3","This is line 3")
print("4","This is line 4")
print("5","This is line 5")
print("6","This is line 6")
print("7","This is line 7")
print("=============================")
print("This concluded the program")

